=== whoana/mint-refactoring/mint-endpoint/src/main/resources/config/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="map">
		<xs:annotation>
			<xs:documentation>데이터 매핑 정의서 포멧 DESIGN</xs:documentation>
		</xs:annotation>
 
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description">
					<xs:annotation>
						<xs:documentation>매핑디스크립션</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="cd" 	type="xs:string"/>	  
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dataset">
					<xs:annotation>
						<xs:documentation>입출력 데이터 소스 정의</xs:documentation>
					</xs:annotation>
					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="source" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="target" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					
				</xs:element>

				<xs:element name="mapping">
					<xs:annotation>
						<xs:documentation>mapping 정의</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="control">
											<xs:complexType>
												<xs:attribute name="id" type="xs:string" />
											</xs:complexType>
										</xs:element>
										 
										
										<xs:element name="input">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="field" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="dataset" type="xs:string" />
															<xs:attribute name="path" 	 type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="output">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="field">
														<xs:complexType>
															<xs:attribute name="dataset" type="xs:string" />
															<xs:attribute name="path" 	 type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== whoana/mint-refactoring/mint-endpoint/SRMAP001.xml
<?xml version="1.0" encoding="UTF-8"?><map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
    <description>
        <name>송수신맵핑1</name>
        <cd>SRMAP001</cd>
    </description>
    <dataset>
        <source id="S001"/>
        <target id="R001"/>
    </dataset>
    <mapping>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/DATA_SIZE"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/DATA_SIZE"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/GLOBAL_ID"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/GLOBAL_ID"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/SVC_ID"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/SVC_ID"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/INTF_ID"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/INTF_ID"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/STATUS"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/STATUS"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/ERROR_CD"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/ERROR_CD"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/CommHeader/FILLER"/>
            </input>
            <output>
                <field dataset="R001" path="/CommHeader/FILLER"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/Data/FIELD01"/>
            </input>
            <output>
                <field dataset="R001" path="/Data/FIELD1"/>
            </output>
        </item>
        <item>
            <control id="move"/>
            <input>
                <field dataset="S001" path="/Data/FIELD02"/>
            </input>
            <output>
                <field dataset="R001" path="/Data/FIELD3"/>
            </output>
        </item>
    </mapping>
</map>
